service:
  name: cryptosquare
app: cryptosquare
org: andeemarks

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline-sns:
    port: 4002 # a free port for the sns server to run on
    debug: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-offline-sns

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  square-sizer-http:
    handler: src/square-sizer/handler.httpFn
    events:
      - http:
          method: get
          path: square-sizer/{plaintext}
          request:
            parameters:
              paths:
                plaintext: true
  square-sizer-sns:
    handler: src/square-sizer/handler.snsFn
    events:
      - sns: 
          arn: arn:aws:sns:ap-southeast-2:123456789012:cs-square-sizer

  normalizer:
    handler: src/normalizer/handler.fn
    events:
      - http:
          method: get
          path: normalizer/{plaintext}
          request:
            parameters:
              paths:
                plaintext: true
      - sns: cs-normalizer

  column-handler:
    handler: src/column-handler/handler.fn
    events:
      - http:
          method: get
          path: column-handler/{plaintext}/{columncount}
          request:
            parameters:
              paths:
                plaintext: true
                columncount: true
      - sns: cs-column-handler
