service:
  name: cryptosquare
app: cryptosquare
org: andeemarks

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  square-sizer:
    handler: src/square-sizer/handler.handler
    events:
      - http:
          method: get
          path: square-sizer
  normalizer:
    handler: src/normalizer/handler.handler
    events:
      - http:
          method: get
          path: normalizer
  column-handler:
    handler: src/column-handler/handler.handler
    events:
      - http:
          method: get
          path: column-handler
